version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apigestao-app
    ports:
      - '4000:4000'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/postgres
    container_name: apigestao-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=apigestao

  redis:
    image: 'bitnami/redis:latest'
    container_name: apigestao-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: apigestao-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db